name: Tag from upstream
on:
  workflow_dispatch:
  schedule:
    - cron: '33 3 * * *'
jobs:
  tag_upstream_release:
    name: Tag latest upstream release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
           token: ${{ secrets.PUSH_TAG_PAT }}
      - name: Get latest local tag
        id: local_release
        uses: actions-ecosystem/action-get-latest-tag@v1
      - name: Get latest upstream release tag
        uses: rez0n/actions-github-release@v1.5
        id: caddy_release
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: caddyserver/caddy
          type: stable
      - name: Tag release if new
        uses: actions-ecosystem/action-push-tag@v1 
        if: ${{ !contains(steps.local_release.outputs.tag, steps.caddy_release.outputs.release) }}
        with:
          tag: ${{ steps.caddy_release.outputs.release }}-mod000
